# Generated by Django 4.2.1 on 2023-05-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250, verbose_name='Название файла фото')),
                ('like_counter', models.IntegerField(verbose_name='Кол-во лайков')),
            ],
        ),
    ]
