# Generated by Django 4.2.1 on 2023-05-31 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_alter_comment_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery_app.photo'),
        ),
    ]
